from tkinter import *
win = Tk()
win.title("나만의 사진첩")
img = PhotoImage(file = "basic.png")
img_lbl = Label()
info_lbl = Label()
guide_lbl = Label(win, text = '파일명과 메모를\n쉼표(,)로 구분지어 작성한 후\nsave 버튼을 클릭하세요', width = 50, height = 5, bg = 'yellow')
img_list = Listbox()
text_box = Text()
save_btn = Button()
#img_lbl.grid(row = 0, column = 0)
#info_lbl.grid(row = 1, column = 0)
#img_list.grid(row = 0, column = 1)
#guide_lbl.grid(row = 1, column = 2)
#text_box.grid(row = 2, column = 2)
#save_btn.grid(row = 2, column = 3)
win.mainloop()
